### ISSUE TITLE
All of ChIP-seq mapping reads are found in both parental strains?

### ISSUE THREAD

**Issue by AlicePsyche** [holtjma/suspenders#2] opened 2016-05-19 01:14 UTC
Hi, 

I am doing ChIP-seq allele specific binding analysis these days but when I finally got the mapping bam file, I found that all of po tag are "3". Is this possible? 

The format of SNP and Indel vcf files used for creating Pseudogenome is something like this, AB strain:

```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  AB
1       1764    .       TGACTAT T       214     .       INDEL;DP=12;VDB=0.0374;AF1=1;AC1=2;DP4=0,0,6,6;MQ=36;FQ=-70.5   GT:PL:GQ        1/1:255,36,0:69
1       1986    .       CC      C       31.4    .       INDEL;DP=4;VDB=0.0301;AF1=1;AC1=2;DP4=0,0,1,2;MQ=34;FQ=-43.5    GT:PL:GQ        1/1:71,9,0:16
1       2632    .       A       AC      16.8    .       INDEL;DP=5;VDB=0.0207;AF1=1;AC1=2;DP4=0,0,1,4;MQ=45;FQ=-49.5    GT:PL:GQ        1/1:57,15,0:25
1       4461    .       ACACACACACA     ACACACACACACA   44.5    .       INDEL;DP=6;VDB=0.0414;AF1=0.5002;AC1=1;DP4=1,0,1,3;MQ=34;FQ=-5.12;PV4=0.4,0.0086,0.032,0.17     GT:PL:GQ        0/1:82,0,31:34
1       4574    .       TGT     T       26.5    .       INDEL;DP=5;VDB=0.0044;AF1=0.5;AC1=1;DP4=1,0,2,0;MQ=43;FQ=7.34;PV4=1,0,0.12,1    GT:PL:GQ        0/1:64,0,41:44
1       5814    .       TACAACACAACACCACACAACACAACACCACACAACACAAC       TACAACACAACACAACACCACACAACACAACACCACACAACACAAC  102     .       INDEL;DP=22;VDB=0.0612;AF1=1;AC1=2;DP4=0,0,2,2;MQ=41;FQ=-46.5   GT:PL:GQ        1/1:142,12,0:21
```

TU strain:

```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  TU
1       1764    .       TGACTAT T       64.5    .       INDEL;DP=6;VDB=0.0343;AF1=0.5;AC1=1;DP4=1,2,1,2;MQ=46;FQ=67.4;PV4=1,9.3e-06,0.023,1     GT:PL:GQ        0/1:102,0,124:99
1       1986    .       CC      C       25.5    .       INDEL;DP=10;VDB=0.0365;AF1=0.5;AC1=1;DP4=4,2,2,2;MQ=44;FQ=28.5;PV4=1,1.8e-05,5.5e-05,0.26       GT:PL:GQ        0/1:63,0,95:66
1       2765    .       G       GTG     22.5    .       INDEL;DP=3;VDB=0.0223;AF1=0.5;AC1=1;DP4=1,0,1,1;MQ=44;FQ=7.31;PV4=1,0.45,0.21,0.096     GT:PL:GQ        0/1:60,0,41:44
1       3415    .       AA      A       66.5    .       INDEL;DP=7;VDB=0.0058;AF1=0.5;AC1=1;DP4=1,2,1,3;MQ=49;FQ=58.1;PV4=1,3.6e-06,0.13,1      GT:PL:GQ        0/1:104,0,93:96
1       3579    .       ACA     A       37.5    .       INDEL;DP=5;VDB=0.0405;AF1=0.5;AC1=1;DP4=1,2,1,1;MQ=48;FQ=40.5;PV4=1,0.00019,0,1 GT:PL:GQ        0/1:75,0,127:78
1       4471    .       A       ACA     20.5    .       INDEL;DP=6;VDB=0.0370;AF1=0.5;AC1=1;DP4=1,2,3,0;MQ=41;FQ=23.5;PV4=0.4,0.33,0.0031,1     GT:PL:GQ        0/1:58,0,110:61
1       4573    .       G       GAGTGTGTG       24.5    .       INDEL;DP=7;VDB=0.0517;AF1=0.5;AC1=1;DP4=2,1,1,1;MQ=46;FQ=27.2;PV4=1,1,0.23,1    GT:PL:GQ        0/1:62,0,73:65
1       4995    .       AC      ACGC    57.5    .       INDEL;DP=18;VDB=0.0730;AF1=0.5001;AC1=1;DP4=4,6,1,4;MQ=21;FQ=-3.28;PV4=0.6,1,1,1        GT:PL:GQ        0/1:95,0,34:37
```

I need to create AB_Pseudogenome and TU_Pseudogenome from reference genome, right? Is there something wrong with my indel vcf file? I noticed that the generated fastq files are exactly the same size(1375900976) but the .mod file are different. Can I check the mod file? Sorry I didn't find the detail documentation of modtools.

**Comment by holtjma** [comment] 2016-05-19 01:54
Hello, how did you build your pseudogenomes?  Did you follow the instructions found on the wiki page for custom pseudogenomes: https://github.com/holtjma/suspenders/wiki/Creating-a-Custom-Pseudogenome

If not, I suggest trying those commands to build the pseudogenomes.  If you already tried that, do the mod files look different?

**Comment by AlicePsyche** [comment] 2016-05-19 04:40
I followed the wiki instruction already but I didn't find a way to see the mod file (the mod file sizes of two strains are different). I know the mod file should be something like this(from your paper of course ;), right?

![mod file](http://database.oxfordjournals.org/content/2014/bau057/F1.large.jpg)

**Comment by holtjma** [comment] 2016-05-19 13:25
When you ran the "vcf2mod" routine, the output is a .mod file specified with the '-o' option.  When created from vcf2mod, it is a plain text file that is human readable and looks similar to the (a) image you posted above.

**Comment by AlicePsyche** [comment] 2016-05-19 17:53
Sorry for the troublesome, I just didn't find a  detail vcf2mod documentation. 

The mod file should be right:

```
#refmeta.chr9=[chr9,58232459,101b8913dc2e87bcedb1581ead691867]
#refmeta.chrM=[chrM,16596,b829fa8418407f7f55e028b78a706eb4]
#sample=AB
s       1       1511    G/C
s       1       1731    T/A
d       1       1764    G
d       1       1765    A
d       1       1766    C
d       1       1767    T
d       1       1768    A
d       1       1769    T
s       1       1984    C/T
d       1       1986    C
s       1       1996    T/G
s       1       2062    T/A
s       1       2134    T/C
s       1       2327    A/G
i       1       2631    C
s       1       2696    C/T
s       1       3209    T/G
```

But when I ran `insilico -o AB.fa AB.mod REF_danRer7.fa` , why there is always _0 line(s) found in MOD_ ?  Does this mean that the AB strain Pseudogenome construction fail? (Sorry I didn't notice this error before...)

```
[2016-05-20 01:33:57] root      : INFO: processing chromosome 'chr10'
[2016-05-20 01:33:57] root      : INFO: 0 line(s) found in MOD
[2016-05-20 01:34:00] root      : INFO: old: 46591166 bp -> new: 46591166 bp
[2016-05-20 01:34:01] root      : INFO: processing chromosome 'chr17'
[2016-05-20 01:34:01] root      : INFO: 0 line(s) found in MOD
[2016-05-20 01:34:05] root      : INFO: old: 53984731 bp -> new: 53984731 bp
[2016-05-20 01:34:06] root      : INFO: processing chromosome 'chr16'
[2016-05-20 01:34:06] root      : INFO: 0 line(s) found in MOD
[2016-05-20 01:34:11] root      : INFO: old: 58780683 bp -> new: 58780683 bp
[2016-05-20 01:34:12] root      : INFO: processing chromosome 'chr15'
[2016-05-20 01:34:12] root      : INFO: 0 line(s) found in MOD
[2016-05-20 01:34:16] root      : INFO: old: 47442429 bp -> new: 47442429 bp
[2016-05-20 01:34:17] root      : INFO: processing chromosome 'chr14'
[2016-05-20 01:34:17] root      : INFO: 0 line(s) found in MOD
[2016-05-20 01:34:21] root      : INFO: old: 53733891 bp -> new: 53733891 bp
[2016-05-20 01:34:23] root      : INFO: processing chromosome 'chr19'
[2016-05-20 01:34:23] root      : INFO: 0 line(s) found in MOD
[2016-05-20 01:34:27] root      : INFO: old: 50254551 bp -> new: 50254551 bp
[2016-05-20 01:34:29] root      : INFO: processing chromosome 'chr18'
[2016-05-20 01:34:29] root      : INFO: 0 line(s) found in MOD
```

**Comment by holtjma** [comment] 2016-05-19 19:44
This likely caused by differences in your chromosomes names.  In the reference metadata you have your chromosomes named with "chr1", "chr2", ..., "chrX".  However, it appears that your VCF files labels these with "1", "2", ..., "X".  When insilico goes to look for lines in the MOD file corresponding to "chr1" it does not find anything because they are all labeled as "1" instead.  In other words, you need to insert consistency in the the naming of your chromosomes or else insilico won't be able to detect the variants from your VCF file.

**Comment by AlicePsyche** [comment] 2016-05-20 06:19
OH! That's the problem! Now I have re-constructed the right Pseudogenomes. I would remap and come back later. Thanks for your help! I should be more careful...

**Comment by holtjma** [comment] 2016-05-20 12:35
Great, I'm marking this as closed.  Feel free to contact me for help or open another ticket if you have code issues

**Closed as completed by holtjma** 2016-05-20 12:35 UTC
